service: moviefansite
provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.secrets.REGION}
  stage: dev
  environment: 
    DB: ${self:custom.secrets.DB}
    APIKEY: ${self:custom.secrets.APIKEY}
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    STAGE: ${self:custom.secrets.STAGE}



functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'



custom:
  secrets: ${file(secrets.json)}

# plugins:
#   - serverless-offline